### ISSUE TITLE
Heading or yaw command in fixed wing using ROS/Gazebo PX4

### ISSUE THREAD

**Issue by joaoalves10** [PX4/sitl_gazebo#803] opened 2021-09-20 13:54 UTC
Hi, i am working on a project which aims to send heading/yaw commands to a fixed wing plane. Right now i am able to send waypoint commands through setpoin_raw/PosistionTarget, however when i try to use the following command: 
rostopic pub -r 5 /mavros/setpoint_raw/attitude mavros_msgs/AttitudeTarget "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
type_mask: 0
orientation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}
body_rate: {x: 0.0, y: 0.0, z: 0.0}
thrust: 0.0"
i do not know what to put in the type_mask and the other parameters to control the heading or yaw. For example, i have the plane flying a certain heading, how can i command it to change its current heding?
 If anyone knows how it is done, or could show me an example of the command i would be grateful.

**Comment by Jaeyoung-Lim** [comment] 2021-09-21 21:27
Closing as duplicate of https://github.com/PX4/PX4-SITL_gazebo/issues/806

**Closed as completed by Jaeyoung-Lim** 2021-09-21 21:27 UTC
