### ISSUE TITLE
Detailed logs in gazebo+mavsim for simulated flights

### ISSUE THREAD

**Issue by Sneha-hub115** [PX4/sitl_gazebo#421] opened 2020-03-04 07:21 UTC
Hi,
I'm using ubuntu18.04 to build the px4 code for gazebo and jmavsim. I'm stuck with the following issues:

    1. How to get detailed logs in gazebo+jmavsim for simulated flights.
    2. How to do diagnostic logging.
    3. How to get detailed logs in QGround control+real drone flight.

Thank you.

**Comment by TSC21** [comment] 2020-03-04 11:20
This is a duplicate of https://github.com/PX4/Firmware/issues/14291. Closing.

**Closed by TSC21** 2020-03-04 11:20 UTC
